/**
 * generate-questions.ts
 * Authors high-quality, concept-teaching questions for the objectives whose source-extracted
 * banks under-taught their grammar concept (OF8, OF13, OF15, OF16, OF19, OF20). Each question
 * is hand-written (correct French, real explanations) and targets the OF's main concept.
 * Items are tagged { generated: true } and injected into content/question-bank/items/OFn.json.
 * Idempotent: existing generated items are replaced on each run.
 *
 * Run: node --experimental-strip-types scripts/generate-questions.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const curriculum = JSON.parse(readFileSync(join(ROOT, "content", "curriculum.json"), "utf8"));
const objOf = (of: number) => curriculum.objectives.find((o: any) => o.of === of);

type MCQ = { concept: string; fr: string; instr: string; options: string[]; why: string; rule: string; dwhy: string[]; tip: string; pattern: string; difficulty?: "easy" | "medium" | "advanced"; vocab?: string };
type FILL = { concept: string; fr: string; instr: string; answer: string[]; why: string; rule: string; tip: string; pattern: string; difficulty?: "easy" | "medium" | "advanced"; vocab?: string };

const SETS: Record<number, (MCQ | FILL)[]> = {
  // ───────────────────────── OF8 — Situer un événement dans le temps ─────────────────────────
  8: [
    { concept: "prepositions", fr: "La réunion commence ___ 9 h.", instr: "Choose the correct preposition of time.", options: ["à", "en", "dans", "le"], why: "On indique l'heure précise avec « à » : à 9 h.", rule: "« à » + heure précise.", dwhy: ["« en » s'emploie avec les mois, saisons et années, pas l'heure.", "« dans » indique un délai futur (dans deux heures).", "« le » introduit une date (le 5 mai) ou un jour habituel."], tip: "à + heure : à 9 h, à midi.", pattern: "à + heure précise." },
    { concept: "prepositions", fr: "Le ministère a ouvert ses portes ___ 1998.", instr: "Choose the correct preposition of time.", options: ["en", "à", "le", "dans"], why: "« en » s'emploie devant une année : en 1998.", rule: "« en » + année / mois / saison (sauf au printemps).", dwhy: ["« à » s'emploie avec l'heure, pas l'année.", "« le » introduit une date complète (le 3 mai), pas une année seule.", "« dans » exprime un délai à venir."], tip: "en 1998, en mai, en été.", pattern: "en + année/mois/saison." },
    { concept: "prepositions", fr: "Nous recevrons une réponse ___ trois jours.", instr: "Choose the preposition that expresses a future delay.", options: ["dans", "depuis", "il y a", "pendant"], why: "« dans » + durée exprime un délai futur : dans trois jours.", rule: "« dans » + durée → moment futur.", dwhy: ["« depuis » marque le début d'une action qui continue.", "« il y a » + durée renvoie au passé (il y a trois jours).", "« pendant » exprime la durée d'une action, pas un délai."], tip: "dans = délai futur ; il y a = passé.", pattern: "dans + durée → futur." },
    { concept: "prepositions", fr: "Le bureau est fermé ___ dimanche (chaque semaine).", instr: "Choose the preposition for a recurring day.", options: ["le", "à", "en", "ce"], why: "« le » + jour de la semaine = action habituelle : le dimanche = tous les dimanches.", rule: "« le » + jour → habitude.", dwhy: ["« à » ne s'emploie pas devant un jour de la semaine.", "« en » s'emploie avec les mois et les saisons.", "« ce » dimanche désigne un dimanche précis, pas une habitude."], tip: "le lundi = tous les lundis.", pattern: "le + jour = habitude." },
    { concept: "prepositions", fr: "Je travaille à la fonction publique ___ 2015.", instr: "Choose the preposition that marks a starting point.", options: ["depuis", "dans", "pendant", "il y a"], why: "« depuis » + date marque le début d'une situation qui dure encore.", rule: "« depuis » → début d'une action toujours en cours.", dwhy: ["« dans » exprime un délai futur.", "« pendant » exprime une durée fermée.", "« il y a » situe un événement ponctuel dans le passé."], tip: "depuis 2015 = et je travaille toujours.", pattern: "depuis + date/durée." },
    { concept: "prepositions", fr: "La formation a duré ___ deux semaines.", instr: "Choose the preposition that expresses duration.", options: ["pendant", "dans", "depuis", "à"], why: "« pendant » + durée exprime la durée complète d'une action : pendant deux semaines.", rule: "« pendant » + durée.", dwhy: ["« dans » exprime un délai futur.", "« depuis » marque le début d'une action qui continue.", "« à » s'emploie avec l'heure."], tip: "pendant = toute la durée.", pattern: "pendant + durée." },
    { concept: "prepositions", fr: "Elle a téléphoné ___ une heure (one hour ago).", instr: "Choose the expression that means 'ago'.", options: ["il y a", "dans", "depuis", "pendant"], why: "« il y a » + durée situe un moment dans le passé : il y a une heure.", rule: "« il y a » + durée → passé.", dwhy: ["« dans » renvoie au futur.", "« depuis » indique une continuité jusqu'à maintenant.", "« pendant » exprime la durée d'une action."], tip: "il y a une heure = one hour ago.", pattern: "il y a + durée → passé." },
    { concept: "question_formation", fr: "___ commence la réunion? — À 14 h.", instr: "Choose the question word that asks about time.", options: ["Quand", "Où", "Comment", "Combien"], why: "« Quand » interroge sur le moment.", rule: "Quand = à quel moment.", dwhy: ["« Où » interroge sur le lieu.", "« Comment » interroge sur la manière.", "« Combien » interroge sur la quantité."], tip: "Quand ? → un moment.", pattern: "Quand + verbe + sujet ?" },
    { concept: "question_formation", fr: "On célèbre la fête du Canada ___ 1er juillet.", instr: "Choose the correct preposition before a full date.", options: ["le", "en", "à", "au"], why: "« le » précède une date complète : le 1er juillet.", rule: "« le » + date complète.", dwhy: ["« en » précède un mois seul (en juillet), pas une date complète.", "« à » s'emploie avec l'heure.", "« au » ne précède pas une date."], tip: "le 1er juillet, le 25 décembre.", pattern: "le + (jour) + mois." },
    { concept: "prepositions", fr: "Les bureaux sont climatisés ___ été.", instr: "Choose the correct preposition for the season.", options: ["en", "au", "le", "à"], why: "On dit « en été », « en automne », « en hiver » — mais « au printemps ».", rule: "en été/automne/hiver ; AU printemps.", dwhy: ["« au » ne s'emploie qu'avec « au printemps ».", "« le » + jour habituel, pas une saison.", "« à » s'emploie avec l'heure."], tip: "en été, mais au printemps.", pattern: "en + saison (sauf printemps)." },
    { concept: "present", fr: "Pour dire l'heure : « ___ deux heures et quart. »", instr: "Choose how to start telling the time.", options: ["Il est", "Il a", "C'est l'", "Il fait"], why: "L'heure se dit avec « il est » : il est deux heures et quart.", rule: "Telling time: « Il est + heure ».", dwhy: ["« Il a » exprime la possession.", "« C'est l' » ne s'emploie pas pour donner l'heure.", "« Il fait » s'emploie pour la météo (il fait beau)."], tip: "Quelle heure est-il ? — Il est…", pattern: "Il est + heure." },
    { concept: "present", fr: "La séance ___ à 9 h précises.", instr: "Choose the correct present-tense form of « commencer ».", options: ["commence", "commencent", "commencer", "commençons"], why: "Sujet singulier « la séance » → 3ᵉ personne du singulier : commence.", rule: "Verbe en -er, 3ᵉ pers. sing. = -e.", dwhy: ["« commencent » est la 3ᵉ personne du pluriel.", "« commencer » est l'infinitif.", "« commençons » est la 1re personne du pluriel."], tip: "il/elle commence.", pattern: "-er → il/elle + -e." },
  ],

  // ───────────────────────── OF13 — Information sur un événement (passé) ─────────────────────────
  13: [
    { concept: "passe_compose", fr: "Hier, nous ___ le rapport avant midi.", instr: "Choose the correct past-tense form.", options: ["avons terminé", "terminions", "avons terminer", "as terminé"], why: "Action ponctuelle et achevée → passé composé : nous avons terminé.", rule: "Passé composé = avoir/être + participe passé.", dwhy: ["« terminions » est l'imparfait (action habituelle ou en cours).", "« avons terminer » : il faut le participe passé « terminé », pas l'infinitif.", "« as terminé » s'emploie avec « tu »."], tip: "avoir + participe passé.", pattern: "nous avons + -é." },
    { concept: "imparfait", fr: "Quand j'étais jeune, j'___ souvent à Ottawa.", instr: "Choose the tense for a past habit.", options: ["allais", "suis allé", "allai", "irais"], why: "Habitude dans le passé → imparfait : j'allais.", rule: "Imparfait = action habituelle ou en cours dans le passé.", dwhy: ["« suis allé » (passé composé) marque une action ponctuelle.", "« allai » est le passé simple, peu employé à l'oral.", "« irais » est le conditionnel."], tip: "souvent / d'habitude → imparfait.", pattern: "j'allais, tu allais…" },
    { concept: "passe_compose", fr: "Elle ___ partie à 17 h.", instr: "Choose the correct auxiliary.", options: ["est", "a", "était", "a été"], why: "« partir » se conjugue avec « être » : elle est partie.", rule: "Verbes de mouvement (partir, aller, venir…) → auxiliaire être.", dwhy: ["« a » : « partir » n'utilise pas « avoir ».", "« était » est l'imparfait de être.", "« a été » est le passé composé de « être », pas de « partir »."], tip: "partir, sortir, venir → être.", pattern: "elle est + participe." },
    { concept: "agreement", fr: "Julie est ___ ce matin (arriver).", instr: "Choose the correctly agreed past participle.", options: ["arrivée", "arrivé", "arrivés", "arriver"], why: "Avec « être », le participe s'accorde avec le sujet : Julie (fém. sing.) → arrivée.", rule: "Passé composé avec être → accord avec le sujet.", dwhy: ["« arrivé » est masculin singulier.", "« arrivés » est masculin pluriel.", "« arriver » est l'infinitif."], tip: "être → accord avec le sujet.", pattern: "elle est arrivée." },
    { concept: "imparfait", fr: "Pendant que je ___, le téléphone a sonné.", instr: "Choose the tense for the background action.", options: ["lisais", "ai lu", "lirai", "lis"], why: "Action en cours (décor) → imparfait : je lisais ; l'événement soudain est au passé composé.", rule: "Imparfait = arrière-plan ; passé composé = événement.", dwhy: ["« ai lu » marque une action achevée, pas le décor.", "« lirai » est le futur.", "« lis » est le présent."], tip: "décor = imparfait, action = passé composé.", pattern: "pendant que … imparfait." },
    { concept: "passe_compose", fr: "L'an dernier, l'équipe ___ trois nouveaux projets.", instr: "Choose the tense for a completed, counted fact.", options: ["a lancé", "lançait", "lance", "lancera"], why: "Fait précis et compté, achevé dans le passé → passé composé : a lancé.", rule: "Fait ponctuel et compté → passé composé.", dwhy: ["« lançait » (imparfait) conviendrait à une habitude, pas à un fait compté.", "« lance » est le présent.", "« lancera » est le futur."], tip: "« trois projets » = fait compté → passé composé.", pattern: "a/ont + -é." },
    { concept: "agreement", fr: "Les lettres que j'ai ___ sont prêtes (écrire).", instr: "Choose the correctly agreed participle (advanced).", options: ["écrites", "écrit", "écrits", "écrite"], why: "Le complément d'objet direct « les lettres » (fém. plur.) est placé AVANT le verbe → accord : écrites.", rule: "Avec avoir, le participe s'accorde avec le COD placé avant le verbe.", dwhy: ["« écrit » : pas d'accord alors que le COD précède.", "« écrits » est masculin pluriel.", "« écrite » est féminin singulier."], tip: "COD avant + avoir → accord.", pattern: "que j'ai écrites.", difficulty: "advanced" },
    { concept: "passe_compose", fr: "Complétez au passé composé : « Hier, il (finir) ___ très tard. »", instr: "Type the passé composé of « finir » for « il ».", answer: ["a fini"], why: "Passé composé de « finir » : auxiliaire avoir + participe « fini » → il a fini.", rule: "finir → participe passé « fini » ; avec avoir.", tip: "il a fini, nous avons fini.", pattern: "avoir + fini." },
  ],

  // ───────────────────────── OF15 — Requête / discours rapporté ─────────────────────────
  15: [
    { concept: "conditionnel", fr: "Pour une demande très polie : « ___-vous m'aider? »", instr: "Choose the most polite (conditional) form.", options: ["Pourriez", "Pourrez", "Pouviez", "Pus"], why: "La demande polie se fait au conditionnel : Pourriez-vous m'aider ?", rule: "Conditionnel de politesse : pourrais, voudrais, aimerais.", dwhy: ["« Pourrez » est le futur.", "« Pouviez » est l'imparfait.", "« Pus » est le passé simple."], tip: "Pourriez-vous… ? = poli.", pattern: "pourrais/-iez + infinitif." },
    { concept: "conditionnel", fr: "Je ___ un renseignement, s'il vous plaît.", instr: "Choose the polite form of « vouloir ».", options: ["voudrais", "veux", "voudrai", "voulais"], why: "« Je voudrais » (conditionnel) atténue la demande et la rend polie.", rule: "« je voudrais » = demande polie.", dwhy: ["« veux » est direct, peu poli.", "« voudrai » est le futur.", "« voulais » est l'imparfait."], tip: "Je voudrais… = I would like…", pattern: "je voudrais + nom/infinitif." },
    { concept: "conditionnel", fr: "À ta place, je ___ le superviseur.", instr: "Choose the tense for giving advice.", options: ["préviendrais", "préviens", "préviendrai", "prévenais"], why: "Un conseil hypothétique se met au conditionnel : je préviendrais.", rule: "Conditionnel = hypothèse / conseil.", dwhy: ["« préviens » est le présent.", "« préviendrai » est le futur.", "« prévenais » est l'imparfait."], tip: "À ta place, je + conditionnel.", pattern: "Si j'étais toi, je …-rais." },
    { concept: "reported_speech", fr: "Il a dit : « Je suis occupé. » → Il a dit qu'il ___ occupé.", instr: "Choose the reported-speech form.", options: ["était", "est", "sera", "soit"], why: "Au discours indirect passé, le présent devient imparfait : qu'il était occupé.", rule: "Style indirect au passé : présent → imparfait.", dwhy: ["« est » : après un verbe introducteur au passé, le présent devient imparfait.", "« sera » est le futur.", "« soit » est le subjonctif, non requis ici."], tip: "présent → imparfait au passé rapporté.", pattern: "il a dit qu'il était…" },
    { concept: "reported_speech", fr: "Elle a annoncé : « Je viendrai. » → Elle a annoncé qu'elle ___.", instr: "Choose the reported-speech form.", options: ["viendrait", "viendra", "venait", "vienne"], why: "Le futur du discours direct devient conditionnel au discours rapporté passé : viendrait.", rule: "Style indirect au passé : futur → conditionnel.", dwhy: ["« viendra » (futur) ne s'emploie pas après un introducteur au passé.", "« venait » rendrait un présent rapporté.", "« vienne » est le subjonctif."], tip: "futur → conditionnel au passé rapporté.", pattern: "elle a dit qu'elle viendrait." },
    { concept: "reported_speech", fr: "Il m'a demandé : « Êtes-vous disponible? » → Il m'a demandé ___ disponible.", instr: "Choose how to report a yes/no question.", options: ["si j'étais", "si je suis", "que j'étais", "est-ce que j'étais"], why: "Une question fermée se rapporte avec « si » + concordance au passé : s'il/si j'étais.", rule: "Question fermée rapportée → « si » ; présent → imparfait.", dwhy: ["« si je suis » : il faut l'imparfait après un introducteur au passé.", "« que j'étais » : on emploie « si », pas « que », pour une question fermée.", "« est-ce que » disparaît au discours indirect."], tip: "question oui/non → « si ».", pattern: "il a demandé si …" },
    { concept: "conditionnel", fr: "Si vous aviez le temps, ___-vous réviser ce texte?", instr: "Choose the verb form after « si + imparfait ».", options: ["pourriez", "pouvez", "pourrez", "puissiez"], why: "Avec « si + imparfait », la principale est au conditionnel : pourriez-vous.", rule: "Si + imparfait, … conditionnel.", dwhy: ["« pouvez » est le présent.", "« pourrez » est le futur.", "« puissiez » est le subjonctif."], tip: "Si + imparfait → conditionnel.", pattern: "Si j'avais…, je ferais…" },
    { concept: "conditionnel", fr: "Demande polie : « Je ___ vous poser une question. » (vouloir)", instr: "Type the polite conditional of « vouloir » for « je ».", answer: ["voudrais"], why: "« Je voudrais » est la forme polie (conditionnel présent de vouloir).", rule: "vouloir → je voudrais (conditionnel).", tip: "Je voudrais… s'il vous plaît.", pattern: "je voudrais + infinitif." },
  ],

  // ───────────────────────── OF16 — Faire une offre / y réagir ─────────────────────────
  16: [
    { concept: "present", fr: "Pour offrir son aide poliment : « ___ vous aider? »", instr: "Choose the polite way to offer help.", options: ["Puis-je", "Je peux-tu", "Est-ce que je dois", "Veux-je"], why: "« Puis-je vous aider? » est la formule polie pour offrir son aide.", rule: "Puis-je + infinitif = offre polie.", dwhy: ["« Je peux-tu » est familier et incorrect à l'écrit standard.", "« Est-ce que je dois » exprime une obligation, pas une offre.", "« Veux-je » n'est pas une tournure usuelle."], tip: "Puis-je vous aider ? = May I help you?", pattern: "Puis-je + infinitif ?" },
    { concept: "present", fr: "— Voulez-vous un café? — ___", instr: "Choose how to accept an offer.", options: ["Oui, volontiers.", "Oui, je dois.", "Non, il faut.", "Oui, je peux-tu."], why: "On accepte une offre par « Oui, volontiers » ou « Avec plaisir ».", rule: "Accepter : Volontiers / Avec plaisir / Oui, merci.", dwhy: ["« Oui, je dois » exprime une obligation.", "« Non, il faut » n'a pas de sens comme réponse.", "« je peux-tu » est familier et incorrect."], tip: "Volontiers ! = Gladly!", pattern: "Oui, volontiers." },
    { concept: "present", fr: "Pour refuser poliment une offre : « ___ »", instr: "Choose the polite refusal.", options: ["Non merci, c'est gentil.", "Non, jamais.", "Je refuse.", "Pas question."], why: "« Non merci, c'est gentil » refuse poliment l'offre.", rule: "Refus poli : Non merci, c'est gentil.", dwhy: ["« Non, jamais » est sec.", "« Je refuse » est abrupt.", "« Pas question » est très familier et impoli."], tip: "Non merci, c'est gentil.", pattern: "Non merci + remerciement." },
    { concept: "present", fr: "Au bureau : « Voulez-vous ___ eau? »", instr: "Choose the correct partitive article.", options: ["de l'", "la", "une", "du"], why: "On offre une quantité indéfinie → partitif « de l' » devant « eau » (féminin, voyelle).", rule: "Offre d'une quantité : du / de la / de l' / des.", dwhy: ["« la » désigne l'eau en général.", "« une » s'emploie avec un nom comptable.", "« du » est masculin (de + le)."], tip: "de l'eau, du café, de la tisane.", pattern: "Voulez-vous + partitif + nom ?" },
    { concept: "passe_compose", fr: "Il m'___ offert son aide hier.", instr: "Choose the correct auxiliary for « offrir ».", options: ["a", "est", "ai", "as"], why: "Passé composé de « offrir » avec avoir : il a offert.", rule: "offrir → avoir + offert.", dwhy: ["« est » : offrir utilise « avoir ».", "« ai » s'emploie avec « je ».", "« as » s'emploie avec « tu »."], tip: "il a offert, nous avons offert.", pattern: "avoir + offert." },
    { concept: "present", fr: "— Puis-je vous offrir quelque chose à boire? — ___", instr: "Choose the polite acceptance.", options: ["Avec plaisir, merci.", "Oui, je veux-tu.", "Non, je dois pas.", "Bien sûr que non."], why: "« Avec plaisir, merci » accepte poliment l'offre.", rule: "Accepter poliment : Avec plaisir.", dwhy: ["« Oui, je veux-tu » est familier et incorrect.", "« Non, je dois pas » est incorrect et impoli.", "« Bien sûr que non » est un refus brusque."], tip: "Avec plaisir ! = With pleasure!", pattern: "Avec plaisir, merci." },
  ],

  // ───────────────────────── OF19 — Évaluer des choses (comparatifs) ─────────────────────────
  19: [
    { concept: "comparatives", fr: "Ce rapport est ___ clair que l'autre : il est plus facile à lire.", instr: "Choose the comparative of superiority.", options: ["plus", "moins", "aussi", "le plus"], why: "Supériorité : plus + adjectif + que.", rule: "plus + adjectif + que = supériorité.", dwhy: ["« moins » exprime l'infériorité.", "« aussi » exprime l'égalité.", "« le plus » forme le superlatif, pas une comparaison entre deux éléments."], tip: "plus … que = more … than.", pattern: "plus + adj + que." },
    { concept: "comparatives", fr: "Cette méthode est ___ efficace que l'ancienne : elle donne de moins bons résultats.", instr: "Choose the comparative of inferiority.", options: ["moins", "plus", "aussi", "la moins"], why: "Infériorité : moins + adjectif + que.", rule: "moins + adjectif + que = infériorité.", dwhy: ["« plus » indiquerait la supériorité, contraire au contexte.", "« aussi » indiquerait l'égalité.", "« la moins » est un superlatif."], tip: "moins … que = less … than.", pattern: "moins + adj + que." },
    { concept: "comparatives", fr: "Mon ordinateur est ___ rapide que le tien : ils ont la même vitesse.", instr: "Choose the comparative of equality.", options: ["aussi", "plus", "moins", "autant"], why: "Égalité avec un adjectif : aussi + adjectif + que.", rule: "aussi + adjectif + que = égalité.", dwhy: ["« plus » = supériorité.", "« moins » = infériorité.", "« autant » s'emploie avec un verbe ou un nom (autant de travail), pas un adjectif."], tip: "aussi … que = as … as.", pattern: "aussi + adj + que." },
    { concept: "comparatives", fr: "Ce logiciel est ___ que l'ancien : il fonctionne beaucoup mieux.", instr: "Choose the comparative of « bon ».", options: ["meilleur", "plus bon", "plus meilleur", "mieux"], why: "Le comparatif de l'adjectif « bon » est « meilleur » (jamais « plus bon »).", rule: "bon → meilleur (comparatif irrégulier).", dwhy: ["« plus bon » est incorrect : on dit « meilleur ».", "« plus meilleur » est un pléonasme.", "« mieux » est le comparatif de l'adverbe « bien », pas de l'adjectif « bon »."], tip: "bon → meilleur ; bien → mieux.", pattern: "meilleur que." },
    { concept: "comparatives", fr: "Elle organise les dossiers ___ que son collègue.", instr: "Choose the comparative of the adverb « bien ».", options: ["mieux", "meilleur", "plus bien", "plus bon"], why: "« mieux » est le comparatif de l'adverbe « bien » et modifie le verbe « organise ».", rule: "bien → mieux.", dwhy: ["« meilleur » est le comparatif de l'adjectif « bon ».", "« plus bien » est incorrect.", "« plus bon » est incorrect."], tip: "un verbe → mieux ; un nom → meilleur.", pattern: "verbe + mieux que." },
    { concept: "comparatives", fr: "C'est le bureau ___ lumineux de tout l'étage.", instr: "Choose the superlative form.", options: ["le plus", "plus", "aussi", "très"], why: "Superlatif de supériorité : le plus + adjectif.", rule: "le / la / les plus + adjectif = superlatif.", dwhy: ["« plus » seul forme un comparatif, pas un superlatif.", "« aussi » exprime l'égalité.", "« très » est un intensif, pas un superlatif relatif."], tip: "le plus … de = the most … of.", pattern: "le plus + adj + de." },
    { concept: "comparatives", fr: "De toutes les imprimantes, c'est ___ : aucune autre n'est aussi bonne.", instr: "Choose the superlative of « bonne ».", options: ["la meilleure", "la plus bonne", "la mieux", "la plus meilleure"], why: "Superlatif de « bon/bonne » = le meilleur / la meilleure.", rule: "bonne → la meilleure.", dwhy: ["« la plus bonne » est incorrect.", "« la mieux » viendrait de « bien », pas de « bonne ».", "« la plus meilleure » est un pléonasme."], tip: "la meilleure = the best.", pattern: "la meilleure de …" },
    { concept: "comparatives", fr: "Il y a ___ documents ici que dans l'autre classeur.", instr: "Choose the comparative used before a noun.", options: ["plus de", "plus", "plus que", "aussi"], why: "Devant un nom, on emploie « plus de » : plus de documents que.", rule: "plus de / moins de / autant de + nom.", dwhy: ["« plus » seul ne précède pas directement le nom dans ce sens.", "« plus que » sans « de » est incorrect devant un nom ici.", "« aussi » s'emploie avec un adjectif, pas un nom."], tip: "plus de + nom + que.", pattern: "plus de + nom." },
    { concept: "comparatives", fr: "Le nouveau modèle coûte ___ cher que l'ancien : le prix est identique.", instr: "Choose the comparative of equality.", options: ["aussi", "plus", "meilleur", "autant"], why: "« cher » est un adjectif → égalité avec « aussi … que ».", rule: "aussi + adjectif + que.", dwhy: ["« plus » = supériorité.", "« meilleur » remplace « plus bon », pas « plus cher ».", "« autant » s'emploie avec un nom ou un verbe."], tip: "aussi cher que = as expensive as.", pattern: "aussi + adj + que." },
    { concept: "comparatives", fr: "Comparatif de « bon » (masc.) : « Ce café est ___ que l'autre. »", instr: "Type the comparative of « bon ».", answer: ["meilleur"], why: "Le comparatif de supériorité de « bon » est « meilleur ».", rule: "bon → meilleur (jamais « plus bon »).", tip: "bon → meilleur.", pattern: "meilleur que." },
  ],

  // ───────────────────────── OF20 — Évaluer des personnes (adjectifs/accord) ─────────────────────────
  20: [
    { concept: "agreement", fr: "Ma collègue est très ___ (compétent).", instr: "Choose the correctly agreed adjective.", options: ["compétente", "compétent", "compétents", "compétentes"], why: "Sujet féminin singulier → adjectif féminin singulier : compétente.", rule: "L'adjectif s'accorde en genre et en nombre avec le nom.", dwhy: ["« compétent » est masculin singulier.", "« compétents » est masculin pluriel.", "« compétentes » est féminin pluriel."], tip: "féminin singulier → +e.", pattern: "elle est compétente." },
    { concept: "agreement", fr: "Les nouveaux employés sont ___ (ponctuel).", instr: "Choose the correctly agreed adjective.", options: ["ponctuels", "ponctuel", "ponctuelle", "ponctuelles"], why: "« employés » est masculin pluriel → ponctuels.", rule: "Masculin pluriel → +s.", dwhy: ["« ponctuel » est masculin singulier.", "« ponctuelle » est féminin singulier.", "« ponctuelles » est féminin pluriel."], tip: "masculin pluriel → +s.", pattern: "ils sont ponctuels." },
    { concept: "agreement", fr: "C'est une directrice ___ (expérimenté).", instr: "Choose the correctly agreed adjective.", options: ["expérimentée", "expérimenté", "expérimentées", "expérimentés"], why: "« directrice » est féminin singulier → expérimentée.", rule: "Féminin singulier → +e.", dwhy: ["« expérimenté » est masculin singulier.", "« expérimentées » est féminin pluriel.", "« expérimentés » est masculin pluriel."], tip: "une directrice expérimentée.", pattern: "féminin singulier → +e." },
    { concept: "adjectives", fr: "Cette analyste est très ___ (sérieux).", instr: "Choose the correct feminine form.", options: ["sérieuse", "sérieux", "sérieuses", "sérieusement"], why: "« sérieux » au féminin singulier = sérieuse.", rule: "-eux → -euse au féminin.", dwhy: ["« sérieux » est masculin.", "« sérieuses » est féminin pluriel.", "« sérieusement » est un adverbe."], tip: "-eux → -euse.", pattern: "sérieux / sérieuse." },
    { concept: "adjectives", fr: "Notre adjointe est très ___ (travailleur).", instr: "Choose the correct feminine form.", options: ["travailleuse", "travailleur", "travailleuses", "travaillante"], why: "« travailleur » au féminin = travailleuse.", rule: "-eur → -euse au féminin (travailleur/travailleuse).", dwhy: ["« travailleur » est masculin.", "« travailleuses » est féminin pluriel.", "« travaillante » n'existe pas."], tip: "-eur → -euse.", pattern: "travailleur / travailleuse." },
    { concept: "adjectives", fr: "C'est un ___ employé : tout le monde l'apprécie.", instr: "Choose the correct word and form.", options: ["bon", "bien", "bonne", "bons"], why: "« bon » est un adjectif placé avant le nom et accordé : un bon employé.", rule: "« bon » (adjectif) précède le nom ; « bien » est un adverbe.", dwhy: ["« bien » est un adverbe, pas un adjectif épithète.", "« bonne » est féminin (or « employé » est masculin).", "« bons » est masculin pluriel."], tip: "un bon/une bonne + nom.", pattern: "un bon employé." },
    { concept: "agreement", fr: "Mes deux superviseurs sont ___ (patient).", instr: "Choose the correctly agreed adjective.", options: ["patients", "patient", "patiente", "patientes"], why: "« superviseurs » est masculin pluriel → patients.", rule: "Masculin pluriel → +s.", dwhy: ["« patient » est masculin singulier.", "« patiente » est féminin singulier.", "« patientes » est féminin pluriel."], tip: "ils sont patients.", pattern: "masculin pluriel → +s." },
    { concept: "agreement", fr: "C'est une équipe ___ (loyal).", instr: "Choose the correctly agreed adjective.", options: ["loyale", "loyal", "loyaux", "loyales"], why: "« équipe » est féminin singulier → loyale.", rule: "Féminin singulier → +e (loyal → loyale).", dwhy: ["« loyal » est masculin singulier.", "« loyaux » est masculin pluriel (-al → -aux).", "« loyales » est féminin pluriel."], tip: "loyal → loyale → loyaux.", pattern: "une équipe loyale." },
    { concept: "agreement", fr: "Accordez : « Ces employées sont très ___ (motivé). »", instr: "Type the adjective agreed for « ces employées » (fem. pl.).", answer: ["motivées"], why: "« employées » est féminin pluriel → motivées (+e +s).", rule: "Féminin pluriel → +es.", tip: "féminin pluriel → +es.", pattern: "elles sont motivées." },
  ],
};

let total = 0;
const summary: Record<string, number> = {};
for (const ofStr of Object.keys(SETS)) {
  const of = Number(ofStr);
  const obj = objOf(of);
  const path = join(ROOT, "content", "question-bank", "items", `OF${of}.json`);
  const bank = JSON.parse(readFileSync(path, "utf8"));
  // drop previously generated items (idempotent)
  bank.items = bank.items.filter((it: any) => !it.generated);

  let n = 0;
  for (const q of SETS[of]) {
    n++;
    const base = {
      id: `itm_of${of}_gen_${n}`, objectiveId: `OF${of}`, generated: true,
      grammarConcepts: [q.concept], vocabDomains: obj?.vocabDomains ?? [], theme: obj?.themes?.[0] ?? "workplace",
      difficulty: q.difficulty ?? "medium", status: "live",
      tip: { memory_aid: q.tip, pattern: q.pattern, similar: ("options" in q ? q.options.slice(0, 2) : q.answer) },
    };
    if ("options" in q) {
      const correct = q.options[0];
      const distractors = [{ value: correct, tag: "correct" }, ...q.options.slice(1).map((o, i) => ({ value: o, tag: `d${i}` }))];
      const distractor_why: Record<string, string> = {};
      q.options.slice(1).forEach((_, i) => { distractor_why[`d${i}`] = q.dwhy[i]; });
      bank.items.push({
        ...base, skill: "grammar", type: "mcq_single", estTimeSec: 30, irtB: 0,
        prompt: { fr: q.fr, instructions_en: q.instr },
        answer: { type: "choice", accepted: [correct], normalizer: "fr_accent_insensitive_trim_lower" },
        distractors,
        explanation: { correct_why: q.why, distractor_why, grammar_rule: q.rule, vocab_notes: q.vocab ?? "Concept enseigné dans cet objectif (PFL2).", common_mistakes: ["choisir une forme proche mais incorrecte"] },
      });
    } else {
      bank.items.push({
        ...base, skill: "writing", type: "fill_blank", estTimeSec: 35, irtB: 0.2,
        prompt: { fr: q.fr, instructions_en: q.instr },
        answer: { type: "text", accepted: q.answer, normalizer: "fr_accent_insensitive_trim_lower" },
        distractors: [],
        explanation: { correct_why: q.why, distractor_why: {}, grammar_rule: q.rule, vocab_notes: q.vocab ?? "Concept enseigné dans cet objectif (PFL2).", common_mistakes: ["se tromper de forme ou d'accord"] },
      });
    }
  }
  if (bank.source?.counts) bank.source.counts.generated = n;
  writeFileSync(path, JSON.stringify(bank));
  summary[`OF${of}`] = n; total += n;
}
console.log(`Generated ${total} new concept-teaching questions:`, JSON.stringify(summary));
